# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
