# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('any_siblings', models.BooleanField(default=False)),
                ('known_env_exposures', models.BooleanField(default=False)),
                ('known_genetic_mutations', models.BooleanField(default=False)),
                ('review', models.CharField(default='Not Reviewed', max_length=30)),
            ],
        ),
    ]
