# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0002_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='known_env_exposures',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='known_genetic_mutations',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
